use crate::metadata::png::PngParseError;
use crate::metadata::png::*;
use std::io::Write;
use std::path::Path;
use tempfile::TempDir;

// Minimal 1x1 red PNG with correct CRC values.
// Generated by taking a real minimal PNG and verifying with pngcheck.
fn create_minimal_png(path: &Path) {
    let png_data: &[u8] = &[
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
        0x00, 0x00, 0x00, 0x0D, // IHDR chunk length
        0x49, 0x48, 0x44, 0x52, // IHDR chunk type
        0x00, 0x00, 0x00, 0x01, // width = 1
        0x00, 0x00, 0x00, 0x01, // height = 1
        0x08, 0x02, // bit depth=8, color type=2 (RGB)
        0x00, 0x00, 0x00, // compression, filter, interlace
        0x90, 0x77, 0x53, 0xDE, // IHDR CRC
        0x00, 0x00, 0x00, 0x0C, // IDAT chunk length
        0x49, 0x44, 0x41, 0x54, // IDAT chunk type
        0x78, 0x01, 0x63, 0x60, 0x60, 0x60, 0x00, 0x00, 0x00, 0x04, 0x00,
        0x01, // compressed data
        0x52, 0x4A, 0xDE, 0x7D, // IDAT CRC
        0x00, 0x00, 0x00, 0x00, // IEND chunk length
        0x49, 0x45, 0x4E, 0x44, // IEND chunk type
        0xAE, 0x42, 0x60, 0x82, // IEND CRC
    ];
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(png_data).unwrap();
}

// Build a PNG with a tEXt chunk embedded before IDAT.
// We manually construct the chunk with correct CRC for test reliability.
fn create_png_with_text_chunk(path: &Path, keyword: &str, value: &str) {
    let mut png_data: Vec<u8> = Vec::new();

    // PNG signature
    png_data.extend_from_slice(&[0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);

    // IHDR chunk (1x1 RGB)
    png_data.extend_from_slice(&[
        0x00, 0x00, 0x00, 0x0D, // length
        0x49, 0x48, 0x44, 0x52, // type
        0x00, 0x00, 0x00, 0x01, // width
        0x00, 0x00, 0x00, 0x01, // height
        0x08, 0x02, // bit depth, color type
        0x00, 0x00, 0x00, // compression, filter, interlace
        0x90, 0x77, 0x53, 0xDE, // CRC
    ]);

    // tEXt chunk: keyword + null separator + text
    let mut text_data: Vec<u8> = Vec::new();
    text_data.extend_from_slice(keyword.as_bytes());
    text_data.push(0x00); // null separator
    text_data.extend_from_slice(value.as_bytes());

    let chunk_len = text_data.len() as u32;
    png_data.extend_from_slice(&chunk_len.to_be_bytes());
    png_data.extend_from_slice(b"tEXt");
    png_data.extend_from_slice(&text_data);

    // CRC for tEXt chunk (type + data)
    let crc_data: Vec<u8> = [b"tEXt", &text_data[..]].concat();
    let crc = crc32fast::hash(&crc_data);
    png_data.extend_from_slice(&crc.to_be_bytes());

    // IDAT chunk (minimal compressed data)
    png_data.extend_from_slice(&[
        0x00, 0x00, 0x00, 0x0C, // length
        0x49, 0x44, 0x41, 0x54, // type
        0x78, 0x01, 0x63, 0x60, 0x60, 0x60, 0x00, 0x00, 0x00, 0x04, 0x00, 0x01, // data
        0x52, 0x4A, 0xDE, 0x7D, // CRC
    ]);

    // IEND chunk
    png_data.extend_from_slice(&[
        0x00, 0x00, 0x00, 0x00, // length
        0x49, 0x45, 0x4E, 0x44, // type
        0xAE, 0x42, 0x60, 0x82, // CRC
    ]);

    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(&png_data).unwrap();
}

// ---- Tests ----

#[test]
fn test_parse_clean_png_no_metadata() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("clean.png");
    create_minimal_png(&path);

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert!(metadata.prompt.is_none(), "no prompt expected");
    assert!(metadata.workflow.is_none(), "no workflow expected");
    assert!(metadata.raw_text_entries.is_empty(), "no text entries expected");
}

#[test]
fn test_parse_corrupt_png() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("corrupt.png");
    std::fs::write(&path, b"this is not a png file").unwrap();

    // Act
    let result = parse_png_metadata(&path);

    // Assert
    assert!(result.is_err(), "corrupt file should error");
    match result.unwrap_err() {
        PngParseError::Png(_) => {}
        other => panic!("expected Png error, got: {:?}", other),
    }
}

#[test]
fn test_parse_nonexistent_file() {
    // Arrange
    let path = Path::new("/nonexistent/file.png");

    // Act
    let result = parse_png_metadata(path);

    // Assert
    assert!(result.is_err(), "nonexistent file should error");
    match result.unwrap_err() {
        PngParseError::Io(_) => {} // expected
        other => panic!("expected Io error, got: {:?}", other),
    }
}

#[test]
fn test_parse_png_with_text_chunk() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("with_text.png");
    create_png_with_text_chunk(&path, "mykey", "myvalue");

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert_eq!(metadata.raw_text_entries.get("mykey"), Some(&"myvalue".to_string()));
    assert!(metadata.prompt.is_none());
    assert!(metadata.workflow.is_none());
}

#[test]
fn test_parse_png_with_prompt_metadata() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("with_prompt.png");
    let prompt_json = r#"{"text":"a beautiful landscape","steps":20}"#;
    create_png_with_text_chunk(&path, "prompt", prompt_json);

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert!(metadata.prompt.is_some(), "prompt should be parsed");
    let prompt = metadata.prompt.unwrap();
    assert_eq!(prompt["text"], "a beautiful landscape");
    assert_eq!(prompt["steps"], 20);
}

#[test]
fn test_parse_png_with_parameters_legacy_key() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("with_parameters.png");
    let params_json = r#"{"positive":"cat","negative":"dog"}"#;
    create_png_with_text_chunk(&path, "parameters", params_json);

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert!(metadata.prompt.is_some(), "parameters should map to prompt");
    let prompt = metadata.prompt.unwrap();
    assert_eq!(prompt["positive"], "cat");
}

#[test]
fn test_parse_png_with_workflow() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("with_workflow.png");
    let workflow_json = r#"{"nodes":[{"id":1,"type":"KSampler"}]}"#;
    create_png_with_text_chunk(&path, "workflow", workflow_json);

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert!(metadata.workflow.is_some(), "workflow should be parsed");
    let workflow = metadata.workflow.unwrap();
    assert_eq!(workflow["nodes"][0]["type"], "KSampler");
}

#[test]
fn test_parse_png_with_non_json_text() {
    // Arrange
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("plain_text.png");
    // Non-JSON plain text in a "prompt" chunk
    create_png_with_text_chunk(&path, "prompt", "some plain text prompt");

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert!(metadata.prompt.is_some(), "non-JSON prompt should still be stored");
    assert_eq!(
        metadata.prompt,
        Some(serde_json::Value::String("some plain text prompt".to_owned()))
    );
}

#[test]
fn test_parse_duplicate_key_takes_first_value() {
    // Arrange: when the same key appears twice, the first value wins
    let dir = TempDir::new().unwrap();
    let path = dir.path().join("prompt_only.png");
    let prompt_json = r#"{"text":"hi"}"#;
    let _workflow_json = r#"{"version":1}"#;
    create_png_with_text_chunk(&path, "prompt", prompt_json);

    // Act
    let metadata = parse_png_metadata(&path).unwrap();

    // Assert
    assert_eq!(metadata.raw_text_entries.len(), 1);
    assert_eq!(metadata.prompt.unwrap()["text"], "hi");
}

#[test]
fn test_metadata_default_is_empty() {
    // Arrange
    let metadata = Metadata::default();

    // Assert
    assert!(metadata.prompt.is_none());
    assert!(metadata.workflow.is_none());
    assert!(metadata.raw_text_entries.is_empty());
}

#[test]
fn test_metadata_serde_roundtrip() {
    // Arrange
    let metadata = Metadata {
        prompt: Some(serde_json::json!({"text": "test"})),
        workflow: None,
        raw_text_entries: [("key".to_string(), "val".to_string())].iter().cloned().collect(),
    };

    // Act
    let json = serde_json::to_string(&metadata).unwrap();
    let deserialized: Metadata = serde_json::from_str(&json).unwrap();

    // Assert
    assert_eq!(deserialized.prompt.unwrap()["text"], "test");
    assert_eq!(deserialized.raw_text_entries.get("key"), Some(&"val".to_string()));
}
