//! Input validation and sanitization helpers for API endpoints.
//!
//! Provides reusable validation functions that return consistent error
//! responses (HTTP 400) with structured JSON error bodies.

use axum::{Json, http::StatusCode};
use serde::Serialize;
use serde_json::{Value, json};

/// A structured error response for validation failures.
#[derive(Debug, Serialize)]
pub struct ValidationError {
    pub error: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<FieldError>>,
}

#[derive(Debug, Serialize)]
pub struct FieldError {
    pub field: String,
    pub message: String,
}

impl ValidationError {
    pub fn new(message: impl Into<String>) -> Self {
        Self { error: message.into(), details: None }
    }

    pub fn with_details(message: impl Into<String>, details: Vec<FieldError>) -> Self {
        Self { error: message.into(), details: Some(details) }
    }

    pub fn into_response(self) -> (StatusCode, Json<Value>) {
        (StatusCode::BAD_REQUEST, Json(json!(self)))
    }
}

impl From<ValidationError> for (StatusCode, Json<Value>) {
    fn from(err: ValidationError) -> Self {
        err.into_response()
    }
}

/// Validate the `limit` query parameter (1..=500).
pub fn validate_limit(limit: u32) -> Result<(), ValidationError> {
    if limit == 0 {
        return Err(ValidationError::new("limit must be positive"));
    }
    if limit > 500 {
        return Err(ValidationError::new(format!("limit must not exceed 500, got {limit}")));
    }
    Ok(())
}

/// Validate the `cursor` query parameter (must be a valid date if present).
///
/// Accepts both RFC 3339 dates (e.g. `2025-01-01T00:00:00Z`) and the
/// application's internal `YYYY-MM-DDTHH:MM:SS` format since cursors are
/// opaque values generated by the API itself.
pub fn validate_cursor(cursor: Option<&str>) -> Result<(), ValidationError> {
    if let Some(c) = cursor
        && !c.is_empty()
    {
        let is_valid = chrono::DateTime::parse_from_rfc3339(c).is_ok()
            || chrono::NaiveDateTime::parse_from_str(c, "%Y-%m-%dT%H:%M:%S").is_ok();
        if !is_valid {
            return Err(ValidationError::new(
                "cursor must be a valid ISO 8601 date string \
                 (e.g. 2025-01-01T00:00:00Z or 2025-01-01T00:00:00)",
            ));
        }
    }
    Ok(())
}

/// Validate the `cursor_id` query parameter (must be UUID v4 format if present).
pub fn validate_cursor_id(cursor_id: Option<&str>) -> Result<(), ValidationError> {
    if let Some(id) = cursor_id
        && !id.is_empty()
        && uuid::Uuid::parse_str(id).is_err()
    {
        return Err(ValidationError::new("cursor_id must be a valid UUID"));
    }
    Ok(())
}

/// Validate a numeric `cursor` query parameter for offset-based pagination.
///
/// Used by the search endpoint.  The cursor represents the number of items
/// already shown (cumulative offset).  Must be a non-negative integer.
pub fn validate_numeric_cursor(cursor: Option<&str>) -> Result<(), ValidationError> {
    if let Some(c) = cursor
        && !c.is_empty()
        && c.parse::<u32>().is_err()
    {
        return Err(ValidationError::new(
            "cursor must be a non-negative integer (cumulative offset)",
        ));
    }
    Ok(())
}

/// Validate the search query `q` parameter.
pub fn validate_search_query(q: &Option<String>) -> Result<(), ValidationError> {
    match q {
        Some(q) if q.trim().is_empty() => {
            Err(ValidationError::new("Query parameter 'q' must not be empty"))
        }
        Some(q) if q.len() > 1000 => {
            Err(ValidationError::new("Query parameter 'q' must not exceed 1000 characters"))
        }
        Some(_) => Ok(()),
        None => Err(ValidationError::new("Query parameter 'q' is required")),
    }
}

/// Validate a media ID path parameter.
pub fn validate_media_id(id: &str) -> Result<(), ValidationError> {
    if id.is_empty() {
        return Err(ValidationError::new("Media ID must not be empty"));
    }
    if id.len() > 128 {
        return Err(ValidationError::new("Media ID must not exceed 128 characters"));
    }
    Ok(())
}

/// Validate a thumbnail width parameter.
pub fn validate_thumbnail_width(width: u32) -> Result<(), ValidationError> {
    if !(100..=500).contains(&width) {
        return Err(ValidationError::new(format!(
            "Width must be between 100 and 500, got {width}"
        )));
    }
    Ok(())
}

/// Validate config watched folder paths.
pub fn validate_watched_folders(
    folders: &[crate::config::WatchedFolder],
) -> Result<(), ValidationError> {
    let mut errors = Vec::new();
    for (i, folder) in folders.iter().enumerate() {
        if folder.path.trim().is_empty() {
            errors.push(FieldError {
                field: format!("watched_folders[{i}].path"),
                message: "Path must not be empty".to_string(),
            });
        }
        if folder.path.contains("..") {
            errors.push(FieldError {
                field: format!("watched_folders[{i}].path"),
                message: "Path must not contain '..' (path traversal)".to_string(),
            });
        }
        if folder.path.len() > 4096 {
            errors.push(FieldError {
                field: format!("watched_folders[{i}].path"),
                message: "Path must not exceed 4096 characters".to_string(),
            });
        }
    }
    if errors.is_empty() {
        Ok(())
    } else {
        Err(ValidationError::with_details("Invalid watched folder configuration", errors))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_limit_ok() {
        assert!(validate_limit(1).is_ok());
        assert!(validate_limit(500).is_ok());
        assert!(validate_limit(100).is_ok());
    }

    #[test]
    fn test_validate_limit_zero() {
        assert!(validate_limit(0).is_err());
    }

    #[test]
    fn test_validate_limit_over_max() {
        assert!(validate_limit(501).is_err());
        assert!(validate_limit(9999).is_err());
    }

    #[test]
    fn test_validate_cursor_valid_iso8601() {
        assert!(validate_cursor(Some("2025-01-01T00:00:00Z")).is_ok());
        assert!(validate_cursor(Some("2025-08-05T14:32:00+00:00")).is_ok());
    }

    #[test]
    fn test_validate_cursor_valid_naivedatetime() {
        // Application's internal date format (no timezone)
        assert!(validate_cursor(Some("2025-06-15T11:58:20")).is_ok());
        assert!(validate_cursor(Some("2026-01-01T00:00:00")).is_ok());
    }

    #[test]
    fn test_validate_cursor_invalid() {
        assert!(validate_cursor(Some("not-a-date")).is_err());
        assert!(validate_cursor(Some("")).is_ok()); // empty is allowed (treated as absent)
    }

    #[test]
    fn test_validate_cursor_none() {
        assert!(validate_cursor(None).is_ok());
    }

    #[test]
    fn test_validate_cursor_id_valid() {
        assert!(validate_cursor_id(Some("550e8400-e29b-41d4-a716-446655440000")).is_ok());
    }

    #[test]
    fn test_validate_cursor_id_invalid() {
        assert!(validate_cursor_id(Some("not-a-uuid")).is_err());
    }

    #[test]
    fn test_validate_cursor_id_none() {
        assert!(validate_cursor_id(None).is_ok());
    }

    #[test]
    fn test_validate_numeric_cursor_valid() {
        assert!(validate_numeric_cursor(Some("0")).is_ok());
        assert!(validate_numeric_cursor(Some("10")).is_ok());
        assert!(validate_numeric_cursor(Some("999999")).is_ok());
    }

    #[test]
    fn test_validate_numeric_cursor_empty_or_none() {
        assert!(validate_numeric_cursor(Some("")).is_ok());
        assert!(validate_numeric_cursor(None).is_ok());
    }

    #[test]
    fn test_validate_numeric_cursor_invalid() {
        assert!(validate_numeric_cursor(Some("-1")).is_err());
        assert!(validate_numeric_cursor(Some("abc")).is_err());
        assert!(validate_numeric_cursor(Some("3.14")).is_err());
    }

    #[test]
    fn test_validate_search_query_ok() {
        assert!(validate_search_query(&Some("hello".to_string())).is_ok());
    }

    #[test]
    fn test_validate_search_query_empty() {
        assert!(validate_search_query(&Some("  ".to_string())).is_err());
    }

    #[test]
    fn test_validate_search_query_none() {
        assert!(validate_search_query(&None).is_err());
    }

    #[test]
    fn test_validate_search_query_too_long() {
        let long = "a".repeat(1001);
        assert!(validate_search_query(&Some(long)).is_err());
    }

    #[test]
    fn test_validate_media_id_ok() {
        assert!(validate_media_id("550e8400-e29b-41d4-a716-446655440000").is_ok());
    }

    #[test]
    fn test_validate_media_id_empty() {
        assert!(validate_media_id("").is_err());
    }

    #[test]
    fn test_validate_thumbnail_width_ok() {
        assert!(validate_thumbnail_width(200).is_ok());
        assert!(validate_thumbnail_width(100).is_ok());
        assert!(validate_thumbnail_width(500).is_ok());
    }

    #[test]
    fn test_validate_thumbnail_width_out_of_range() {
        assert!(validate_thumbnail_width(50).is_err());
        assert!(validate_thumbnail_width(501).is_err());
    }

    #[test]
    fn test_validate_watched_folders_ok() {
        use crate::config::WatchedFolder;
        let folders =
            vec![WatchedFolder { path: "/media/photos".to_string(), label: None, id: None }];
        assert!(validate_watched_folders(&folders).is_ok());
    }

    #[test]
    fn test_validate_watched_folders_empty_path() {
        use crate::config::WatchedFolder;
        let folders = vec![WatchedFolder { path: "".to_string(), label: None, id: None }];
        assert!(validate_watched_folders(&folders).is_err());
    }

    #[test]
    fn test_validate_watched_folders_path_traversal() {
        use crate::config::WatchedFolder;
        let folders =
            vec![WatchedFolder { path: "/media/../../etc".to_string(), label: None, id: None }];
        assert!(validate_watched_folders(&folders).is_err());
    }

    #[test]
    fn test_validation_error_response_format() {
        let err = ValidationError::new("test error");
        let (status, json) = err.into_response();
        assert_eq!(status, StatusCode::BAD_REQUEST);
        let val = json.0;
        assert_eq!(val["error"], "test error");
    }
}
